fail-if-warnings: true
project:
  type: book
  pre-render:
    - _extensions/Afonenko-Course-Tools/course-core/entrypoints/pre.ts
  post-render: _extensions/Afonenko-Course-Tools/course-core/entrypoints/post.ts
  output-dir: _book
  resources:
    - "!projects/**"
book:
  title: Служба на виртуальной машине
  repo-url: https://github.com/Afonenko-Course-Tools/quarto-course-cloud
  repo-subdir: examples/course
  repo-actions: [source]
  repo-branch: demo-20261007-ru1
  chapters:
    - index.qmd
    - tasks/index.qmd
    - labs/01.qmd
format:
  html:
    theme: cosmo
    code-tools: false
lang: ru
course:
  id: demo-cloud
  validate: true
  adapters: [cloud]
filters:
  - course-core
  - course-cloud
profile:
  default: full
  group: [[student, full]]

bibliography: references.bib
