project:
  type: book
  pre-render:
    - _extensions/course-core/entrypoints/pre.ts
    - _extensions/course-core/entrypoints/owner-freeze.ts
  post-render: _extensions/course-core/entrypoints/post.ts
  output-dir: _book
  resources:
    - "!projects/**"
book:
  title: Служба на виртуальной машине
  chapters:
    - index.qmd
    - tasks/index.qmd
    - labs/01.qmd
format:
  html:
    theme: cosmo
lang: ru
course:
  id: demo-cloud
  validate: true
  adapters: [cloud]
filters:
  - course-core
  - course-cloud
profile:
  default: student
  group: [[student, full]]
